In [ ]:
#Block Matching By Hadi Abdelmawla

In [4]:
import numpy as np
import argparse
import cv2

import matplotlib.pyplot as plt

import tensorflow as tf

In [5]:
imageTable = np.array([[178,228,14,164,246,210,82,79,14,157,230,154,145,204,28,178],
                       [239,104,202,194,64,21,225,182,255,50,100,215,75,177,118,239],
                       [216,155,78,195,38,3,105,101,92,172,179,24,21,43,172,216],
                       [110,99,189,54,187,86,29,167,32,140,91,189,10,46,123,110],
                       [28,172,166,157,34,35,18,118,74,241,119,88,146,92,212,28],
                       [61,97,165,129,222,93,223,56,57,215,155,242,102,121,249,61],
                       [149,69,22,220,77,146,47,68,232,203,16,221,150,65,225,149],
                       [135,100,192,110,174,131,41,248,141,124,19,178,180,201,51,135],
                       [251,117,102,31,57,161,146,123,244,161,61,51,41,33,158,251],
                       [47,235,136,252,186,65,145,138,159,228,169,195,66,244,56,47],
                       [165,63,194,127,53,79,3,21,85,8,185,41,212,141,38,165],
                       [20,249,177,38,50,227,156,144,49,41,230,245,49,245,253,20],
                       [195,121,21,95,197,243,116,230,235,4,86,204,191,148,150,195],
                       [224,26,207,78,12,95,189,67,105,72,212,215,245,249,60,224],
                       [5,8,7,98,233,176,124,251,220,129,82,236,222,137,7,5],
                       [178,228,14,164,246,210,82,79,14,157,230,154,145,204,28,178]])

searchTemplate = np.array([[123, 250,185],[170,24,20], [117,102,31]] )


In [133]:
#code for part a
def fullsearch(xrange,yrange,w,imageTable, squaresize):
    w = np.zeros((15,15))
    x=0
    z=0
    for (i) in range (xrange[0],xrange[1]):
        #print(i)
        for j in range (yrange[0],yrange[1]):
         #   print (j)
        #print(i)
            w[i][j] = imageTable[i][j]
            z=z+1
            if (z==squaresize):
                z=0
        x=x+1
    maxvalue = np.amax(w)
    index = np.where(w == np.amax(w))
    return maxvalue, index

In [135]:
#calling the part a function
xrange = [0,7]
yrange = [0,7]
default = [0,7]
shape = imageTable.shape

square = 7
v = 0
partAmax = dict()
partAindext = dict()
for i in shape:
    if xrange[1]< shape[0]:
        for j in shape:
            if yrange[1]<shape[1]:

                partAmax[v], partAindext[v] = fullsearch(xrange,yrange, w, imageTable,square)
                #print(v)
                v=v+1
                print(v)                
                yrange = [yrange[0]+square, yrange[1]+square]
                #print(yrange)
        if yrange[1]>shape[1]:
            yrange = default
        xrange =[xrange[0]+square, xrange[1]+square]




print(partAmax)
print(partAindext)

1
2
3
4
{0: 246.0, 1: 255.0, 2: 252.0, 3: 249.0}
{0: (array([0]), array([4])), 1: (array([1]), array([8])), 2: (array([9]), array([3])), 3: (array([13]), array([13]))}


In [154]:
#function used for the rest of the parts
def threess(xrange,yrange,imageTable,squaresize,testarray):
    w = np.zeros((15,15))
    x=0
    z=0
    for (i) in range (xrange[0],xrange[1]):
        #print(i)
        for j in range (yrange[0],yrange[1]):
         #   print (j)
        #print(i)
            if(i>(squaresize)):
                x = i-7
            if(j>(squaresize)):
                z = j-7
            if(testarray[x][z]==0):
                continue
            w[i][j] = imageTable[i][j]
            
            #z=z+1
            #if (z==squaresize):
             #   z=0
        #x=x+1
    maxvalue = np.amax(w)
    index = np.where(w == np.amax(w))
    return maxvalue, index

In [155]:
#Creating the arrays neccessary for part B code is self explanatory
array = np.zeros((7,7))
array[0,0]=1
array[0,3] = 1
array[0,6] = 1
array[3,0] = 1
array[6,0] = 1
array[3,3] = 1
array[6,3] = 1
array[6,6] = 1
xrange = [0,7]
yrange = [0,7]
default = [0,7]
shape = imageTable.shape

square = 7
v = 0
partBmaxone = dict()
partBindexone = dict()
for i in shape:
    if xrange[1]< shape[0]:
        for j in shape:
            if yrange[1]<shape[1]:
                partBmaxone[v], partBindexone[v] = threess(xrange,yrange,imageTable,square,array)
                #print(v)
                v=v+1
                print(v)                
                yrange = [yrange[0]+square, yrange[1]+square]
                #print(yrange)
        if yrange[1]>shape[1]:
            yrange = default
        xrange =[xrange[0]+square, xrange[1]+square]
print(partBindexone)
print(partBmaxone)

1
2
3
4
{0: (array([0]), array([4])), 1: (array([0]), array([10])), 2: (array([13]), array([0])), 3: (array([13]), array([13]))}
{0: 246.0, 1: 230.0, 2: 224.0, 3: 249.0}


In [158]:
#code for part B stage 2
twoarray =  np.zeros((5,5))
twoarray[0,0] = 1
twoarray[2,0]=1
twoarray[4,0]=1
twoarray[0,2]=1
twoarray[2,2]=1
twoarray[4,2]=1
twoarray[0,4]=1
twoarray[2,4]=1
twoarray[4,4]=1
xrange = [0,5]
yrange = [0,5]
default = [0,5]
v = 0
partBmaxtwo = dict()
partBindextwo = dict()
for i in shape:
    if xrange[1]< shape[0]:
        for j in shape:
            if yrange[1]<shape[1]:
                partBmaxtwo[v], partBindextwo[v] = threess(xrange,yrange,imageTable,square,twoarray)
                #print(v)
                v=v+1
                print(v)                
                yrange = [yrange[0]+square, yrange[1]+square]
                #print(yrange)
        if yrange[1]>shape[1]:
            yrange = default
        xrange =[xrange[0]+square, xrange[1]+square]
print(partBindextwo)
print(partBmaxtwo)

1
2
3
4
{0: (array([0]), array([4])), 1: (array([4]), array([9])), 2: (array([9]), array([3])), 3: (array([7]), array([7]))}
{0: 246.0, 1: 241.0, 2: 252.0, 3: 248.0}


In [159]:
#code for part B stage 3
thirdarray = np.ones((3,3))
xrange = [0,3]
yrange = [0,3]
default = [0,3]
v = 0
partBmaxthree = dict()
partBindexthree = dict()
for i in shape:
    if xrange[1]< shape[0]:
        for j in shape:
            if yrange[1]<shape[1]:
                partBmaxthree[v], partBindexthree[v] = threess(xrange,yrange,imageTable,square,thirdarray)
                #print(v)
                v=v+1
                print(v)                
                yrange = [yrange[0]+square, yrange[1]+square]
                #print(yrange)
        if yrange[1]>shape[1]:
            yrange = default
        xrange =[xrange[0]+square, xrange[1]+square]
print(partBindexthree)
print(partBmaxthree)

1
2
3
4
{0: (array([1]), array([0])), 1: (array([1]), array([8])), 2: (array([8]), array([0])), 3: (array([7]), array([7]))}
{0: 239.0, 1: 255.0, 2: 251.0, 3: 248.0}


In [161]:
#code for part C stage 1
xrange = [5,11]
yrange = [5,11]
partCmaxone = dict
partCindexone = dict
partCmaxone, partCindexone = threess(xrange,yrange,imageTable,square,twoarray)
print(partCindexone)
print(partCmaxone)

(array([9]), array([9]))
228.0


In [162]:
#code for part C stage 4 since the other stages are repeat of the above
partCarray = np.zeros((5,5))
partCarray[1,1]=1
partCarray[1,2]=1
partCarray[1,3]=1
partCarray[2,1]=1
partCarray[2,2]=1
partCarray[2,3]=1
partCarray[3,1]=1
partCarray[3,2]=1
partCarray[3,3]=1
xrange = [5,11]
yrange = [5,11]
partCmaxthree = dict
partCindexthree = dict
partCmaxthree, partCindexthree = threess(xrange,yrange,imageTable,square,twoarray)
print(partCindexthree)
print(partCmaxthree)

(array([9]), array([9]))
228.0


In [187]:
#code used from online github diamond array
#code for part E stage 1
N       = 5
H       = abs(np.arange(1-N,N+1,2))//2
V       = H[0] - H[:,None]
diamond = (H==V)*1
diamond[2,2]=1
print(diamond)
xrange = [5,11]
yrange = [5,11]
partEmaxone = dict
partEindexone = dict
partEmaxone, partEindexone = threess(xrange,yrange,imageTable,square,diamond)
print(partEindexone)
print(partEmaxone)

[[0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]]
(array([8]), array([8]))
244.0


In [188]:
#code for stage 2
f = [partEindexone[0]-3,partEindexone[1]+3]
h = int(f[0])
g = int(f[1])
xrange = [h,g]
yrange = [h,g]
partEmaxtwo = dict
partEindextwo = dict
partEmaxtwo, partEindextwo = threess(xrange,yrange,imageTable,square,diamond)
print(partEindextwo)
print(partEmaxtwo)

(array([8]), array([8]))
244.0


In [189]:
#code for stage 3
f = [partEindextwo[0]-3,partEindextwo[1]+3]
h = int(f[0])
g = int(f[1])
xrange = [h,g]
yrange = [h,g]
partEmaxthree = dict
partEindexthree = dict
partEmaxthree, partEindexthree = threess(xrange,yrange,imageTable,square,diamond)
print(partEindexthree)
print(partEmaxthree)

(array([8]), array([8]))
244.0


In [190]:
#code for stage 4
partearray = np.zeros((5,5))
partearray[1,2]=1
partearray[2,1]=1
partearray[2,2]=1
partearray[2,3]=1
partearray[3,2]=1
f = [partEindexthree[0]-3,partEindextwo[1]+3]
h = int(f[0])
g = int(f[1])
xrange = [h,g]
yrange = [h,g]
partEmaxfour = dict
partEindexfour = dict
partEmaxfour, partEindexfour = threess(xrange,yrange,imageTable,square,partearray)
print(partEindexfour)
print(partEmaxfour)


(array([9]), array([9]))
228.0


In [191]:
#code for stage 1 part D 
partdarray = np.zeros((5,5))
partdarray[0,1]=1
partdarray[0,3]=1
partdarray[2,0]=1
partdarray[2,2]=1
partdarray[2,4]=1
partdarray[4,1]=1
partdarray[4,3]=1
xrange = [5,11]
yrange = [5,11]
partDmaxone = dict
partDindexone = dict
partDmaxone, partDindexone = threess(xrange,yrange,imageTable,square,partdarray)
print(partDindexone)
print(partDmaxone)

(array([7]), array([7]))
248.0


In [192]:
#code for stage 2
f = [partDindexone[0]-3,partDindexone[1]+3]
h = int(f[0])
g = int(f[1])
xrange = [h,g]
yrange = [h,g]
partDmaxtwo = dict
partDindextwo = dict
partDmaxtwo, partDindextwo = threess(xrange,yrange,imageTable,square,partdarray)
print(partDindextwo)
print(partDmaxtwo)

(array([6]), array([8]))
232.0


In [193]:
#stage 3
f = [partDindextwo[0]-3,partDindextwo[1]+3]
h = int(f[0])
g = int(f[1])
xrange = [h,g]
yrange = [h,g]
partDmaxthree = dict
partDindexthree = dict
partDmaxthree, partDindexthree = threess(xrange,yrange,imageTable,square,partdarray)
print(partDindexthree)
print(partDmaxthree)

(array([7]), array([7]))
248.0


In [194]:
#stage 4
f = [partDindexthree[0]-3,partDindextwo[1]+3]
h = int(f[0])
g = int(f[1])
xrange = [h,g]
yrange = [h,g]
partDmaxfour = dict
partDindexfour = dict
partDmaxfour, partDindexfour = threess(xrange,yrange,imageTable,square,partearray)
print(partDindexfour)
print(partDmaxfour)

(array([9]), array([9]))
228.0
